node:
    build: .
    command: node app.js
    environment:
        - DEBUG=*
    ports:
        - "4000:4000"
    links:
        - mongo
mongo:
    image: mongo:3.2.9
    volumes:
        - /data/db:/data/db
